# Generated by Django 5.2 on 2025-04-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carb', 'Carbohydrate'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy')], max_length=50)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('prioritize', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
